name: CI/CD Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Backend Image
      run: docker build -t rahma33986/rental-backend:latest ./backend

    - name: Build Frontend Image
      run: docker build -t rahma33986/rental-frontend:latest ./frontend

    - name: Scan Backend Image
      uses: aquasecurity/trivy-action@v2
      with:
        image-ref: rahma33986/rental-backend:latest
        scan-type: image

    - name: Scan Frontend Image
      uses: aquasecurity/trivy-action@v2
      with:
        image-ref: rahma33986/rental-frontend:latest
        scan-type: image

    - name: Push Backend Image
      run: docker push rahma33986/rental-backend:latest

    - name: Push Frontend Image
      run: docker push rahma33986/rental-frontend:latest
